version: '3.8'

services:
  bazaar-app:
    container_name: bazaar_frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - trioverse-network

networks:
  trioverse-network:
    external: true